USE Parc;

CREATE TABLE IF NOT EXISTS Segment (
    indIP VARCHAR(45) PRIMARY KEY,
    nomSegment VARCHAR(30) NOT NULL,
    etage INT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Salle (
    nSalle VARCHAR(255) PRIMARY KEY,
    nomSalle VARCHAR(30) NOT NULL,
    nbPoste INT,
    indIP VARCHAR(45),
    FOREIGN KEY (indIP) REFERENCES Segment(indIP) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Poste (
    nPoste VARCHAR(255) PRIMARY KEY,
    nomPoste VARCHAR(30) NOT NULL,
    indIP VARCHAR(45),
    ad INT,
    typePoste VARCHAR(30),
    nSalle VARCHAR(255),
    FOREIGN KEY (indIP) REFERENCES Segment(indIP) ON DELETE SET NULL,
    FOREIGN KEY (nSalle) REFERENCES Salle(nSalle) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Logiciel (
    nLog VARCHAR(255) PRIMARY KEY,
    nomLog VARCHAR(30) NOT NULL,
    dateAch DATE,
    version VARCHAR(30),
    typeLog VARCHAR(30),
    prix DECIMAL(10,2) CHECK (prix >= 0)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Installer (
    numIns INT AUTO_INCREMENT PRIMARY KEY,
    nPoste VARCHAR(255),
    nLog VARCHAR(255),
    dateIns DATETIME DEFAULT CURRENT_TIMESTAMP,
    delai INT,
    FOREIGN KEY (nPoste) REFERENCES Poste(nPoste) ON DELETE CASCADE,
    FOREIGN KEY (nLog) REFERENCES Logiciel(nLog) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Types (
    typeLP VARCHAR(30) NOT NULL PRIMARY KEY,
    nomType VARCHAR(50) NOT NULL
) ENGINE=InnoDB;

SHOW TABLES;
