USE Parc;

DROP TABLE IF EXISTS Installer;
DROP TABLE IF EXISTS Logiciel;
DROP TABLE IF EXISTS Poste;
DROP TABLE IF EXISTS Salle;
DROP TABLE IF EXISTS Segment;
DROP TABLE IF EXISTS Types;

SHOW TABLES;

SELECT nSalle, indIP FROM Salle WHERE indIP NOT IN (SELECT indIP FROM Segment);
SELECT nLog, typeLog FROM Logiciel WHERE typeLog NOT IN (SELECT typeLP FROM Types);