/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;


public class Accueil extends javax.swing.JFrame {

    /**
     * Creates new form Accueil
     */
    public Accueil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        playButton = new javax.swing.JButton();
        newGameButton = new javax.swing.JButton();
        myRestoButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 800));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(3, 1, 0, 8));

        playButton.setBackground(new java.awt.Color(204, 255, 204));
        playButton.setFont(new java.awt.Font("LM Sans 9", 1, 48)); // NOI18N
        playButton.setText("PLAY");
        playButton.setBorder(null);
        playButton.setBorderPainted(false);
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });
        jPanel1.add(playButton);

        newGameButton.setBackground(new java.awt.Color(255, 204, 204));
        newGameButton.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        newGameButton.setText("New GAME");
        newGameButton.setActionCommand("NEW GAME");
        newGameButton.setBorder(null);
        newGameButton.setBorderPainted(false);
        jPanel1.add(newGameButton);

        myRestoButton.setBackground(new java.awt.Color(255, 204, 153));
        myRestoButton.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        myRestoButton.setText("MY RESTO");
        myRestoButton.setBorder(null);
        myRestoButton.setBorderPainted(false);
        jPanel1.add(myRestoButton);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 620, 460));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pizza-3007395.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        // TODO add your handling code here:
        WelcomeDJ  wind= new WelcomeDJ(this,true); 
        wind.setLocation(100,100);// definition de sa position par rapport au coins supérieur gauche de l'écran
        wind.setVisible(true);    //  jDialog rendu visible 
    }//GEN-LAST:event_playButtonActionPerformed



    /**
     * @param args the command line arguments
     */
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton myRestoButton;
    private javax.swing.JButton newGameButton;
    private javax.swing.JButton playButton;
    // End of variables declaration//GEN-END:variables
}
