/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

import controller.InventoryController;
import model.Pizza;
import model.Commande;
import controller.CommandController;
import controller.MenuController; 
import controller.FicheLivraisonControlle; 
import controller.DashboardController; 


/**
 *
 * @author kokoudevops
 */
public class OrderBoard extends javax.swing.JFrame {

    private InventoryController inventoryController;
    private CommandController commandeController;
    private MenuController menuController; 
    private FicheLivraisonControlle flivs; 
    private DashboardController dash ; 

    /**
     * Creates new form OrderBoard
     */
    public OrderBoard() {
        initComponents();
        inventoryController = new InventoryController(this);
        commandeController = new CommandController();
        menuController= new MenuController(); 
        flivs = new FicheLivraisonControlle(); 
        dash= new DashboardController(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Gauche = new javax.swing.JPanel();
        commande = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        currentCommand = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstCmdAttent = new javax.swing.JList<>();
        Centre = new javax.swing.JPanel();
        CNord = new javax.swing.JPanel();
        soldeText = new javax.swing.JLabel();
        CCentreListPizza = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        photoPiz = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        detailPiz = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        photoPiz1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        detailPiz1 = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        photoPiz2 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        detailPiz2 = new javax.swing.JTextArea();
        CSud = new javax.swing.JPanel();
        SNord = new javax.swing.JPanel();
        btSizeS = new javax.swing.JButton();
        btSizeM = new javax.swing.JButton();
        btSizeL = new javax.swing.JButton();
        SSud = new javax.swing.JPanel();
        btValider = new javax.swing.JButton();
        Droite = new javax.swing.JPanel();
        btInventaire = new javax.swing.JButton();
        btDashB = new javax.swing.JButton();
        btMenu = new javax.swing.JButton();
        btFiche = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listCmdPrete = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1256, 650));
        setResizable(false);

        Gauche.setPreferredSize(new java.awt.Dimension(280, 1000));

        commande.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        commande.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        commande.setText("COMMANDES");
        commande.setPreferredSize(new java.awt.Dimension(120, 40));
        Gauche.add(commande);

        jScrollPane4.setFocusable(false);
        jScrollPane4.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jScrollPane4.setPreferredSize(new java.awt.Dimension(250, 120));

        currentCommand.setColumns(20);
        currentCommand.setRows(5);
        currentCommand.setAutoscrolls(false);
        currentCommand.setFocusable(false);
        currentCommand.setMinimumSize(new java.awt.Dimension(10, 10));
        currentCommand.setPreferredSize(new java.awt.Dimension(80, 80));
        jScrollPane4.setViewportView(currentCommand);

        Gauche.add(jScrollPane4);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(250, 450));

        jScrollPane2.setViewportView(lstCmdAttent);

        Gauche.add(jScrollPane2);

        getContentPane().add(Gauche, java.awt.BorderLayout.WEST);

        Centre.setLayout(new java.awt.BorderLayout(0, 30));

        CNord.setPreferredSize(new java.awt.Dimension(613, 50));

        soldeText.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        soldeText.setText("Solde Actuel: 10 000€");

        javax.swing.GroupLayout CNordLayout = new javax.swing.GroupLayout(CNord);
        CNord.setLayout(CNordLayout);
        CNordLayout.setHorizontalGroup(
            CNordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 613, Short.MAX_VALUE)
            .addGroup(CNordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CNordLayout.createSequentialGroup()
                    .addContainerGap(189, Short.MAX_VALUE)
                    .addComponent(soldeText)
                    .addContainerGap(189, Short.MAX_VALUE)))
        );
        CNordLayout.setVerticalGroup(
            CNordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
            .addGroup(CNordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CNordLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(soldeText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        Centre.add(CNord, java.awt.BorderLayout.NORTH);

        CCentreListPizza.setLayout(new java.awt.GridLayout(3, 1, 0, 5));

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        photoPiz.setForeground(new java.awt.Color(255, 255, 255));
        photoPiz.setIcon(new javax.swing.ImageIcon("/home/kokoudevops/Documents/BD/Rapizz_Pizzeria/src/images/Margherita.jpeg")); // NOI18N
        photoPiz.setBorder(null);
        photoPiz.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        photoPiz.setPreferredSize(new java.awt.Dimension(290, 174));
        photoPiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photoPizActionPerformed(evt);
            }
        });
        jPanel1.add(photoPiz);

        detailPiz.setColumns(20);
        detailPiz.setRows(5);
        detailPiz.setText("Margherita\n15€");
        detailPiz.setAutoscrolls(false);
        detailPiz.setFocusable(false);
        jScrollPane1.setViewportView(detailPiz);

        jPanel1.add(jScrollPane1);

        CCentreListPizza.add(jPanel1);

        jPanel4.setLayout(new java.awt.GridLayout(1, 2));

        photoPiz1.setForeground(new java.awt.Color(255, 255, 255));
        photoPiz1.setIcon(new javax.swing.ImageIcon("/home/kokoudevops/Documents/BD/Rapizz_Pizzeria/src/images/Margherita.jpeg")); // NOI18N
        photoPiz1.setBorder(null);
        photoPiz1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        photoPiz1.setPreferredSize(new java.awt.Dimension(290, 174));
        photoPiz1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photoPiz1ActionPerformed(evt);
            }
        });
        jPanel4.add(photoPiz1);

        detailPiz1.setColumns(20);
        detailPiz1.setRows(5);
        detailPiz1.setText("Margherita\n15€");
        detailPiz1.setAutoscrolls(false);
        detailPiz1.setFocusable(false);
        jScrollPane5.setViewportView(detailPiz1);

        jPanel4.add(jScrollPane5);

        CCentreListPizza.add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(1, 2));

        photoPiz2.setForeground(new java.awt.Color(255, 255, 255));
        photoPiz2.setIcon(new javax.swing.ImageIcon("/home/kokoudevops/Documents/BD/Rapizz_Pizzeria/src/images/Margherita.jpeg")); // NOI18N
        photoPiz2.setBorder(null);
        photoPiz2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        photoPiz2.setPreferredSize(new java.awt.Dimension(290, 174));
        photoPiz2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photoPiz2ActionPerformed(evt);
            }
        });
        jPanel5.add(photoPiz2);

        detailPiz2.setColumns(20);
        detailPiz2.setRows(5);
        detailPiz2.setText("Margherita\n15€");
        detailPiz2.setAutoscrolls(false);
        detailPiz2.setFocusable(false);
        jScrollPane6.setViewportView(detailPiz2);

        jPanel5.add(jScrollPane6);

        CCentreListPizza.add(jPanel5);

        Centre.add(CCentreListPizza, java.awt.BorderLayout.CENTER);

        CSud.setLayout(new java.awt.BorderLayout());

        SNord.setLayout(new java.awt.GridLayout(1, 3));

        btSizeS.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        btSizeS.setText("S");
        btSizeS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSizeSActionPerformed(evt);
            }
        });
        SNord.add(btSizeS);

        btSizeM.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        btSizeM.setText("M");
        SNord.add(btSizeM);

        btSizeL.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        btSizeL.setText("L");
        SNord.add(btSizeL);

        CSud.add(SNord, java.awt.BorderLayout.NORTH);

        btValider.setBackground(new java.awt.Color(51, 153, 0));
        btValider.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        btValider.setForeground(new java.awt.Color(255, 255, 255));
        btValider.setText("VALIDER");

        javax.swing.GroupLayout SSudLayout = new javax.swing.GroupLayout(SSud);
        SSud.setLayout(SSudLayout);
        SSudLayout.setHorizontalGroup(
            SSudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 613, Short.MAX_VALUE)
            .addGroup(SSudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SSudLayout.createSequentialGroup()
                    .addContainerGap(239, Short.MAX_VALUE)
                    .addComponent(btValider)
                    .addContainerGap(239, Short.MAX_VALUE)))
        );
        SSudLayout.setVerticalGroup(
            SSudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(SSudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SSudLayout.createSequentialGroup()
                    .addContainerGap(36, Short.MAX_VALUE)
                    .addComponent(btValider, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(15, 15, 15)))
        );

        CSud.add(SSud, java.awt.BorderLayout.SOUTH);

        Centre.add(CSud, java.awt.BorderLayout.SOUTH);

        getContentPane().add(Centre, java.awt.BorderLayout.CENTER);

        Droite.setMinimumSize(new java.awt.Dimension(34, 34));
        Droite.setPreferredSize(new java.awt.Dimension(280, 759));
        Droite.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 30));

        btInventaire.setText("INVENTAIRE");
        btInventaire.setMargin(new java.awt.Insets(2, 32, 2, 32));
        btInventaire.setMinimumSize(new java.awt.Dimension(24, 24));
        btInventaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInventaireActionPerformed(evt);
            }
        });
        Droite.add(btInventaire);

        btDashB.setText("DASHBOARD");
        btDashB.setMargin(new java.awt.Insets(2, 30, 2, 30));
        btDashB.setMinimumSize(new java.awt.Dimension(24, 24));
        btDashB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDashBActionPerformed(evt);
            }
        });
        Droite.add(btDashB);

        btMenu.setLabel("MENU");
        btMenu.setMargin(new java.awt.Insets(2, 50, 2, 50));
        btMenu.setMaximumSize(new java.awt.Dimension(155, 24));
        btMenu.setMinimumSize(new java.awt.Dimension(24, 24));
        btMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuActionPerformed(evt);
            }
        });
        Droite.add(btMenu);

        btFiche.setText("Fiche livraison");
        btFiche.setMargin(new java.awt.Insets(2, 24, 2, 24));
        btFiche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFicheActionPerformed(evt);
            }
        });
        Droite.add(btFiche);

        jScrollPane3.setPreferredSize(new java.awt.Dimension(250, 410));

        listCmdPrete.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "N°: 0011", "N°: 0013", "N°: 0018", "N°: 0021" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listCmdPrete.setPreferredSize(new java.awt.Dimension(200, 370));
        jScrollPane3.setViewportView(listCmdPrete);

        Droite.add(jScrollPane3);

        getContentPane().add(Droite, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSizeSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSizeSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSizeSActionPerformed

    private void photoPizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photoPizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_photoPizActionPerformed

    private void photoPiz1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photoPiz1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_photoPiz1ActionPerformed

    private void photoPiz2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photoPiz2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_photoPiz2ActionPerformed

    private void btInventaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInventaireActionPerformed
        inventoryController.showInventoryWindow();
    }//GEN-LAST:event_btInventaireActionPerformed

    private void btMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuActionPerformed
        // TODO add your handling code here:
        menuController.showMenuWindow();       
    }//GEN-LAST:event_btMenuActionPerformed

    private void btDashBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDashBActionPerformed
        // TODO add your handling code here:
        dash.showDash(); 
    }//GEN-LAST:event_btDashBActionPerformed

    private void btFicheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFicheActionPerformed
        // TODO add your handling code here:
        flivs.showFicheLivraison(); 
    }//GEN-LAST:event_btFicheActionPerformed
    public void setSolde(double solde) {
        soldeText.setText("Solde Actuel: " + solde + "€");
    }

    public void setListPizza(ArrayList<Pizza> listPizza) {
        CCentreListPizza.removeAll();
        CCentreListPizza.setLayout(new java.awt.GridLayout(listPizza.size(), 1, 0, 5));

        for (Pizza pizza : listPizza) {
            JPanel pizzaPanel = new JPanel(new java.awt.GridLayout(1, 2));
            JButton pizzaImage = new JButton();
            pizzaImage.setIcon(new javax.swing.ImageIcon("src/images/" + pizza.getImagePath())); // Assuming Pizza has getImagePath()
            pizzaImage.setBorder(null);
            pizzaImage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

            JTextArea pizzaDetails = new JTextArea();
            pizzaDetails.setText(pizza.getName() + "\n" + pizza.getPrice() + "€"); // Assuming Pizza has getName() and getPrice()
            pizzaDetails.setFocusable(false);
            pizzaDetails.setAutoscrolls(false);

            pizzaPanel.add(pizzaImage);
            pizzaPanel.add(new JScrollPane(pizzaDetails));
            CCentreListPizza.add(pizzaPanel);
        }

        CCentreListPizza.revalidate();
        CCentreListPizza.repaint();
    }

    public void setListCmdPrete(ArrayList<Pizza> listPizza)
    {
        
    }
    public void setListCmdAttent() {
        ArrayList<Commande> commandes = commandeController.getRandomCmd();
        DefaultListModel<String> model = new DefaultListModel<>();
        for (Commande commande : commandes) {
            model.addElement(commande.getNomClient() + " - N°: " + commande.getNumeroCommande());
        }
        lstCmdAttent.setModel(model);
    }
    public void setCurrentCommand(String commande) {
        currentCommand.setText(commande);
    }

    // /**
    //  * @param args the command line arguments
    //  */
    // public static void main(String args[]) {
    //     /* Set the Nimbus look and feel */
    //     //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    //     /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
    //      * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
    //      */
    //     try {
    //         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    //             if ("Nimbus".equals(info.getName())) {
    //                 javax.swing.UIManager.setLookAndFeel(info.getClassName());
    //                 break;
    //             }
    //         }
    //     } catch (ClassNotFoundException ex) {
    //         java.util.logging.Logger.getLogger(OrderBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (InstantiationException ex) {
    //         java.util.logging.Logger.getLogger(OrderBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (IllegalAccessException ex) {
    //         java.util.logging.Logger.getLogger(OrderBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    //         java.util.logging.Logger.getLogger(OrderBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     }
    //     //</editor-fold>

    //     /* Create and display the form */
    //     java.awt.EventQueue.invokeLater(new Runnable() {
    //         public void run() {
    //             new OrderBoard().setVisible(true);
    //         }
    //     });
    // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CCentreListPizza;
    private javax.swing.JPanel CNord;
    private javax.swing.JPanel CSud;
    private javax.swing.JPanel Centre;
    private javax.swing.JPanel Droite;
    private javax.swing.JPanel Gauche;
    private javax.swing.JPanel SNord;
    private javax.swing.JPanel SSud;
    private javax.swing.JButton btDashB;
    private javax.swing.JButton btFiche;
    private javax.swing.JButton btInventaire;
    private javax.swing.JButton btMenu;
    private javax.swing.JButton btSizeL;
    private javax.swing.JButton btSizeM;
    private javax.swing.JButton btSizeS;
    private javax.swing.JButton btValider;
    private javax.swing.JLabel commande;
    private javax.swing.JTextArea currentCommand;
    private javax.swing.JTextArea detailPiz;
    private javax.swing.JTextArea detailPiz1;
    private javax.swing.JTextArea detailPiz2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JList<String> listCmdPrete;
    private javax.swing.JList<String> lstCmdAttent;
    private javax.swing.JButton photoPiz;
    private javax.swing.JButton photoPiz1;
    private javax.swing.JButton photoPiz2;
    private javax.swing.JLabel soldeText;
    // End of variables declaration//GEN-END:variables
}
