-- TOUS LES CHAMPS SONT A REMPLACER PAR LES VALEURS A INSERER

-- Pour insérer un client
INSERT INTO CLIENT VALUES ([NUMERO_ABONNE], [NOM], [PRENOM], [ADRESSE], [SOLDE], [NOMBRE_COMMANDES]);

-- Pour insérer une pizza
INSERT INTO PIZZA VALUES ([ID_PIZZA], [NOM], [PRIX_BASE]);

-- Pour insérer un ingrédient
INSERT INTO INGREDIENT VALUES ([ID_INGREDIENT], [NOM], [ALLERGENE]);

-- Pour insérer un véhicule
INSERT INTO VEHICULE VALUES ([ID_VEHICULE], [TYPE], [IMMATRICULATION], [NOMBRE_LIVRAISONS], [DUREE]);

-- Pour insérer un livreur
INSERT INTO LIVREUR VALUES ([ID_LIVREUR], [NOM], [PRENOM], [NOMBRE_LIVRAISONS], [DUREE_LIVRAISONS]);

-- Pour insérer une commande
INSERT INTO COMMANDE VALUES ([NUM_COMMANDE], [DATE_COMMANDE], [MONTANT], [NUMERO_ABONNE]);

-- Pour insérer une livraison
INSERT INTO LIVRAISON VALUES ([ID_LIVRAISON], [DATE_LIVRAISON], [DUREE_MINUTES], [ADRESSE_LIVRAISON]);

-- Pour lier une commande à une pizza 
INSERT INTO COMMANDER VALUES ([NUM_COMMANDE], [ID_PIZZA], [TAILLE_PIZZA]);

-- Pour composer une pizza avec des ingrédients 
INSERT INTO COMPOSER VALUES ([ID_PIZZA], [ID_INGREDIENT]);

-- Pour associer une commande à une livraison
INSERT INTO LIVRER VALUES ([NUM_COMMANDE], [ID_LIVRAISON]);

-- Pour associer un livreur à un véhicule
INSERT INTO UTILISER VALUES ([ID_LIVREUR], [ID_VEHICULE]);